{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_server_requests_seconds_count{error=\"none\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(http_server_requests_seconds_count{error!=\"none\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum by(err) (rate(nginx_ingress_controller_nginx_process_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{container=\"k-app-container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"k-app-container\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}