openapi: 3.0.0
info:
  description: |
    This is simple client API
  version: "1.1.0"
  title: User Service
servers:
  - description: Local
    url: http://127.0.0.1:8081/api/v1
tags:
  - name: login
    description: Login ops
  - name: user
    description: Operations about user
paths:
  /login:
    post:
      tags:
        - login
      summary: Login as user
      operationId: login
      responses:
        default:
          description: JWT token
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              sample-user:
                summary: Example
                value:
                  username: "johndoe589"
                  password: "12345"
        description: Login data
        required: true
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      responses:
        200:
          description: successful operation
        default:
          description: error
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              sample-user:
                summary: Example
                value:
                  username: johndoe589
                  password: 123456
                  firstName: John
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71002003040'
        description: Created user object
        required: true
  /user/{userId}:
    parameters:
      - name: userId
        in: path
        description: ID of user
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - user
      description: Returns a user based on a single ID, if the user does not have access to the user
      operationId: find user by id
      security:
        - BearerAuth: []
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: error
          content:
            text/plain:
              schema:
                type: string
    delete:
      tags:
        - user
      description: deletes a single user based on the ID supplied
      operationId: deleteUser
      security:
        - BearerAuth: []
      responses:
        '204':
          description: user deleted
        default:
          description: error
          content:
            text/plain:
              schema:
                type: string
    put:
      tags:
        - user
      description: Update user with User ID supplied
      operationId: updateUser
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              sample-user:
                summary: Example
                value:
                  firstName: Julie
                  lastName: Doe
                  email: bestjohn@doe.com
                  phone: '+71004242424'

      responses:
        '200':
          description: user updated
        default:
          description: error
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          maxLength: 256
        password:
          type: string
          maxLength: 256
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
          format: phone
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          maxLength: 256
        password:
          type: string
          maxLength: 256

  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true
    LoginRequest:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true