kind: PersistentVolume
apiVersion: v1
metadata:
  name: k-postgres-deployment-container-vol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/hw6"