apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresServicePath }}
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgresServicePort }}
      targetPort: {{ .Values.postgresServicePort }}
