apiVersion: v1
kind: ConfigMap
metadata:
  name: k-app-configmap
data:
  spring.datasource.url: "jdbc:postgresql://{{ .Values.postgresServicePath }}:{{ .Values.postgresServicePort}}/postgres"
  server.error.include-message: "always"