kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k-postgres-deployment-container-vol-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi